name: Release

on:
  release:
    types: [published]

env:
  JAVA_TOOL_OPTIONS: -Xmx5120m
  TERM: dumb

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Save/Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build Velocidapter
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publish -PmavenCentralRepositoryUsername=${{ github.actor }} -PmavenCentralRepositoryPassword=${{ secrets.GITHUB_TOKEN }} -PVERSION_NAME=${GITHUB_REF##*v}
